Fix/config
coMakeIT-TIC/jhipster-blueprints pull request #16
Opened 2023-06-29 12:20 UTC by Sri-Harsha06

2023-06-29 17:07 UTC, craxkumar requested changes
We would required .env file for the mainfest files to work, 
Let's discuss tomorrow!

2023-06-29 17:07 UTC, craxkumar commented on generator-jhipster-gomicro/generators/server/templates/gomicro/gomicro/config/config_yaml.go
> +package app
Change the package name to the one which is set by end user

2023-06-29 17:07 UTC, craxkumar commented on generator-jhipster-gomicro/generators/server/templates/gomicro/gomicro/config/config_yaml.go
> +func Setconfig(){
So this file contains the methods/logic to load the configuration based on the env variable passed, so let's name the file as configLoader.go rather then config_yaml.go

2023-06-29 17:07 UTC, craxkumar commented on generator-jhipster-gomicro/generators/server/templates/gomicro/gomicro/dev-config.yaml
> +GO_MICRO_SERVICE_PORT : <%= serverPort %>
Let's keep all the yaml files in one palce, all the .yml files can go in the config dir.  For good user readability.

2023-07-03 05:01 UTC, Sri-Harsha06 commented on generator-jhipster-gomicro/generators/server/templates/gomicro/gomicro/config/config_yaml.go
> +package app
This is like a module not the global package name as we are not taking this as input from the user it is predefined.

2023-07-03 09:21 UTC, craxkumar requested changes

2023-07-03 09:21 UTC, craxkumar commented on generator-jhipster-gomicro/generators/server/templates/gomicro/gomicro/config/configLoader.go
> +var g map[string]interface{}
change it to some useful name

2023-07-03 09:21 UTC, craxkumar commented on generator-jhipster-gomicro/generators/server/templates/gomicro/gomicro/config/configLoader.go
> +	c, _ := config.NewConfig(
change it to meaning full name

2023-07-03 09:21 UTC, craxkumar commented on generator-jhipster-gomicro/generators/server/templates/gomicro/gomicro/eurekaregistry/EurekaRegistrationManager.go
> +		//set this as hostname for local environment
remove this comment

2023-07-03 09:38 UTC, craxkumar approved these changes
Review OK!

2023-07-03 09:39 UTC, merged