Added gomigrate for database versioning
coMakeIT-TIC/jhipster-blueprints pull request #24
Opened 2023-07-28 12:07 UTC by Sri-Harsha06

2023-07-28 15:09 UTC, rohithteja-cmi commented on generator-jhipster-gomicro/generators/server/templates/gomicro/gomicro/migrate/migrate.go
> +func generateurl(databaseUrl, defaultDatabaseName, newDatabaseName string) string {
generateUrl - case methods

2023-07-30 09:04 UTC, craxkumar requested changes

2023-07-30 09:04 UTC, craxkumar commented on generator-jhipster-gomicro/generators/server/templates/gomicro/gomicro/migrate/migration/000001_init_schema.down.sql
> +DROP TABLE IF EXISTS event;
this is the first time the database will be created so there is no chance that the event table would exist from the starting 
right ?

2023-07-30 09:04 UTC, craxkumar commented on generator-jhipster-gomicro/generators/server/templates/gomicro/gomicro/migrate/migrate.go
> +	_ "github.com/golang-migrate/migrate/v4/database/postgres"
so this migrate.go file is for postgress specific so lets name it as postgress.go which will be under the migrate dir, so lets say in future we are have migrate file for the mongo then we will can have mongo.go under the migrate dir!
which will make the end user clear that those dir contains migrate files

2023-07-31 04:26 UTC, Sri-Harsha06 commented on generator-jhipster-gomicro/generators/server/templates/gomicro/gomicro/migrate/migration/000001_init_schema.down.sql
> +DROP TABLE IF EXISTS event;
No actually here, the "down" file is used to define the reverse actions that should be taken to undo the changes made by a specific migration's "up" file.So here in the case we want to roll back to previous version  the specific down file  here is to reverse what we have done in the up file by creating a table.

2023-07-31 09:43 UTC, craxkumar approved these changes
Review OK!

2023-07-31 14:35 UTC, rohithteja-cmi approved these changes

2023-07-31 14:35 UTC, merged