- Keycloak added response codes and messages for error
coMakeIT-TIC/jhipster-blueprints pull request #30
Opened 2023-09-11 06:32 UTC by Sri-Harsha06

- Grouped config(.yml) files under resources folder
- Removed few logs
-  Deleted unwanted files from the generated application

2023-09-11 10:58 UTC, craxkumar requested changes

2023-09-11 10:58 UTC, craxkumar commented on generator-jhipster-gomicro/generators/server/generator.mjs
> +      throw new Error(`This is a JHipster blueprint and should be used only like ${chalk.yellow('jhipster --blueprints test')}`);
jhipster --blueprints test

change this to 
jhipster --blueprints gomicro

2023-09-11 10:58 UTC, craxkumar commented on generator-jhipster-gomicro/generators/server/templates/gomicro/gomicro/auth/auth.go
> +			json.NewEncoder(w).Encode("Token is not active")
u can simply say:-

 Invalid token
or 
token expired

2023-09-11 10:58 UTC, craxkumar commented on generator-jhipster-gomicro/generators/server/templates/gomicro/gomicro/eurekaregistry/helper/HttpHelper.go
> -	logger.Infof(msg)
why remove a log for the POST call for eureka ?

2023-09-11 10:58 UTC, craxkumar commented on generator-jhipster-gomicro/generators/server/templates/gomicro/gomicro/eurekaregistry/helper/HttpHelper.go
> -	msg := fmt.Sprintf("In MakePostCall to %s with body %s", urlToPost, body)
why remove a log for the PUT call for eureka ?
in spring boot application provided by the Jhipster we do have logs for it !

2023-09-14 07:23 UTC, rohithteja-cmi commented on generator-jhipster-gomicro/generators/server/generator.mjs
> +          { src: 'ReadMe.md', dest: 'ReadMe.md' },
README.md

2023-09-14 07:23 UTC, rohithteja-cmi commented on generator-jhipster-gomicro/package-lock.json
please remove this file and add in git ignore as well.

2023-09-14 11:03 UTC, craxkumar approved these changes
Review OK!

2023-09-14 11:04 UTC, merged