Docusaurus
coMakeIT-TIC/jhipster-blueprints pull request #31
Opened 2023-09-14 06:26 UTC by Harsha9198

docusaurus generator

2023-09-14 07:22 UTC, craxkumar requested changes

2023-09-14 07:22 UTC, craxkumar commented on docusaurus-generator/generators/templates/docusaurus/README.md
> +Once the server is up and running, open your web browser and visit http://localhost:3000/ to see the locally running Docusaurus documentation site.
default file be 3000,
but we will take the user input as for port number which will be dynamically render 
so lets better go with json

2023-09-15 08:01 UTC, rohithteja-cmi approved these changes

2023-09-15 10:53 UTC, craxkumar approved these changes
Review OK!

2023-09-15 10:54 UTC, merged